### ISSUE TITLE
`click_on` vs `click_link` and `click_button`

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop-capybara#58]
Reference: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/actions.rb

There is no information which style is preferred.

1.
```ruby
click_link 'New Project'
click_button 'Save'
```

2.

```ruby
click_on 'New Project'
click_on 'Save'
```

**Comment by ydah** [comment]
Consider also that click_on is an alias for click_link_or_button.

**Comment by iainbeeston** [comment]
Can someone explain the rationale behind why using `click_link` and `click_button` is better than `click_link_or_button` and `click_on`? Maybe I'm missing something here, but I would have expected `click_on` and `click_link_or_button` to be better because your tests will be less tightly coupled to your HTML and it more closely reflects how a user would behave (there's no way a user can tell the difference between a button and a link styled to look like a button)
